#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path


VALID_EXTENSIONS = {".png", ".jpg", ".jpeg", ".webp"}


def build_manifest(source_dir: Path) -> dict[str, str]:
    manifest: dict[str, str] = {}
    for path in sorted(source_dir.iterdir(), key=lambda p: p.name):
        if not path.is_file():
            continue
        if path.suffix.lower() not in VALID_EXTENSIONS:
            continue
        if not path.stem.isdigit():
            continue
        manifest[path.stem] = path.name
    return manifest


def render_typescript(manifest: dict[str, str], source_dir: Path) -> str:
    lines = [
        "// Generated by scripts/generate_player_image_manifest.py",
        f"// Source: {source_dir}",
        f"// Entries: {len(manifest)}",
        "",
        "export const PLAYER_IMAGE_MANIFEST: Record<string, string> = {",
    ]
    for player_id, file_name in manifest.items():
        lines.append(f'  "{player_id}": "{file_name}",')
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a lightweight player image manifest for the web app.")
    parser.add_argument("--source", default="src/players", help="Directory containing player image files")
    parser.add_argument("--target", default="src/playerImageManifest.ts", help="TypeScript file to write")
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[1]
    source_dir = (repo_root / args.source).resolve()
    target_path = (repo_root / args.target).resolve()

    if not source_dir.exists():
        raise FileNotFoundError(f"Source directory not found: {source_dir}")

    manifest = build_manifest(source_dir)
    target_path.write_text(render_typescript(manifest, source_dir), encoding="utf-8")
    print(f"Wrote {len(manifest)} image entries to {target_path}")


if __name__ == "__main__":
    main()
